services:
  postgres:
    image: postgres:17.9-alpine
    container_name: postgres17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplebank_api
    env_file:
      - ./app.env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_SOURCE: postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    ports:
      - "8080:8080"
